CREATE TABLE IF NOT EXISTS image_generation_message
(
    id                  BIGINT       NOT NULL PRIMARY KEY,
    userId              BIGINT       NOT NULL,
    conversationId      VARCHAR(64)  NOT NULL,
    role                VARCHAR(32)  NOT NULL,
    prompt              TEXT         NULL,
    aspectRatio         VARCHAR(16)  NULL,
    referenceImageUrl   VARCHAR(1024) NULL,
    sourcePromptAssetId BIGINT       NULL,
    taskId              VARCHAR(64)  NULL,
    status              VARCHAR(32)  NOT NULL DEFAULT 'pending',
    providerCode        VARCHAR(64)  NULL,
    providerName        VARCHAR(128) NULL,
    modelCode           VARCHAR(64)  NULL,
    vendorModel         VARCHAR(64)  NULL,
    imageSize           VARCHAR(16)  NULL,
    vendorSize          VARCHAR(32)  NULL,
    imageCount          INT          NULL,
    pointCost           INT          NULL,
    apiCostCny          DECIMAL(10, 2) NULL,
    pointStatus         VARCHAR(32)  NULL,
    startedTime         DATETIME     NULL,
    finishedTime        DATETIME     NULL,
    resultImageUrls     TEXT         NULL,
    requestPayload      TEXT         NULL,
    responsePayload     TEXT         NULL,
    errorMessage        TEXT         NULL,
    createTime          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete            TINYINT      NOT NULL DEFAULT 0,
    KEY idx_img_gen_user_conversation (userId, conversationId),
    KEY idx_img_gen_user_create (userId, createTime),
    KEY idx_img_gen_task (taskId),
    KEY idx_img_gen_status (status),
    KEY idx_img_gen_provider (providerCode),
    KEY idx_img_gen_model_size (modelCode, imageSize),
    KEY idx_img_gen_role_status_create (role, status, createTime)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT 'image generation conversation messages';
