-- Prompt asset library schema for importing visual_prompt_library.db.
-- Apply this SQL to the admin MySQL database before enabling imports.

CREATE TABLE IF NOT EXISTS prompt_asset (
    id BIGINT NOT NULL PRIMARY KEY,
    assetType VARCHAR(32) NOT NULL COMMENT 'image_prompt / video_prompt',
    categoryId BIGINT DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(512) DEFAULT NULL,
    promptContent MEDIUMTEXT NOT NULL,
    promptCn MEDIUMTEXT DEFAULT NULL,
    coverUrl VARCHAR(1024) DEFAULT NULL,
    previewMediaUrl VARCHAR(1024) DEFAULT NULL,
    mediaType VARCHAR(32) DEFAULT 'image',
    sourceName VARCHAR(64) DEFAULT 'visual_prompt_library',
    sourcePairId BIGINT DEFAULT NULL,
    sourceRepoId BIGINT DEFAULT NULL,
    sourceRepoName VARCHAR(255) DEFAULT NULL,
    sourceRepoUrl VARCHAR(1024) DEFAULT NULL,
    sourcePageUrl VARCHAR(1024) DEFAULT NULL,
    sourceImageOriginalUrl VARCHAR(1024) DEFAULT NULL,
    sourceImageLocalPath VARCHAR(1024) DEFAULT NULL,
    sourceImageHash VARCHAR(128) DEFAULT NULL,
    sourceCloudStorageUrl VARCHAR(1024) DEFAULT NULL,
    sourceThumbnailLocalPath VARCHAR(1024) DEFAULT NULL,
    sourceThumbnailCloudStorageUrl VARCHAR(1024) DEFAULT NULL,
    cloudStorageProvider VARCHAR(64) DEFAULT NULL,
    cloudStorageBucket VARCHAR(128) DEFAULT NULL,
    cloudStorageRegion VARCHAR(64) DEFAULT NULL,
    cloudStorageKey VARCHAR(512) DEFAULT NULL,
    cloudUploadedAt VARCHAR(64) DEFAULT NULL,
    visualAssetType VARCHAR(64) DEFAULT NULL,
    scenario VARCHAR(128) DEFAULT NULL,
    visualStyle VARCHAR(255) DEFAULT NULL,
    qualityLevel VARCHAR(64) DEFAULT 'pending_review',
    selectionStatus VARCHAR(64) DEFAULT 'pending_review',
    license VARCHAR(128) DEFAULT NULL,
    commercialRisk VARCHAR(128) DEFAULT 'unknown',
    memberOnly TINYINT DEFAULT 0,
    status TINYINT DEFAULT 0 COMMENT '0 draft, 1 published, 2 archived',
    sort INT DEFAULT 0,
    syncKey VARCHAR(128) NOT NULL,
    sourceCreatedAt VARCHAR(64) DEFAULT NULL,
    sourceUpdatedAt VARCHAR(64) DEFAULT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT DEFAULT 0,
    UNIQUE KEY uk_prompt_asset_sync_key (syncKey),
    KEY idx_prompt_asset_asset_type (assetType),
    KEY idx_prompt_asset_category_id (categoryId),
    KEY idx_prompt_asset_visual_type (visualAssetType),
    KEY idx_prompt_asset_selection (selectionStatus),
    KEY idx_prompt_asset_status (status),
    KEY idx_prompt_asset_source_hash (sourceImageHash),
    KEY idx_prompt_asset_cloud_storage_url (sourceCloudStorageUrl(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prompt_asset_media (
    id BIGINT NOT NULL PRIMARY KEY,
    promptAssetId BIGINT NOT NULL,
    mediaType VARCHAR(32) DEFAULT 'image',
    originalUrl VARCHAR(1024) DEFAULT NULL,
    localUrl VARCHAR(1024) DEFAULT NULL,
    cloudUrl VARCHAR(1024) DEFAULT NULL,
    thumbnailLocalUrl VARCHAR(1024) DEFAULT NULL,
    thumbnailCloudUrl VARCHAR(1024) DEFAULT NULL,
    sourceLocalPath VARCHAR(1024) DEFAULT NULL,
    fileHash VARCHAR(128) DEFAULT NULL,
    cloudStorageProvider VARCHAR(64) DEFAULT NULL,
    cloudStorageBucket VARCHAR(128) DEFAULT NULL,
    cloudStorageRegion VARCHAR(64) DEFAULT NULL,
    cloudStorageKey VARCHAR(512) DEFAULT NULL,
    cloudUploadedAt VARCHAR(64) DEFAULT NULL,
    width INT DEFAULT NULL,
    height INT DEFAULT NULL,
    fileSize BIGINT DEFAULT NULL,
    sort INT DEFAULT 0,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    isDelete TINYINT DEFAULT 0,
    UNIQUE KEY uk_prompt_asset_media_hash (promptAssetId, fileHash),
    KEY idx_prompt_asset_media_asset_id (promptAssetId),
    KEY idx_prompt_asset_media_type (mediaType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prompt_asset_tag (
    id BIGINT NOT NULL PRIMARY KEY,
    promptAssetId BIGINT NOT NULL,
    tagId BIGINT NOT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_prompt_asset_tag (promptAssetId, tagId),
    KEY idx_prompt_asset_tag_asset_id (promptAssetId),
    KEY idx_prompt_asset_tag_tag_id (tagId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prompt_asset_import_batch (
    id BIGINT NOT NULL PRIMARY KEY,
    sourceName VARCHAR(64) DEFAULT 'visual_prompt_library',
    sourceDbName VARCHAR(255) DEFAULT NULL,
    importMode VARCHAR(32) DEFAULT 'incremental',
    assetTypeFilter VARCHAR(32) DEFAULT NULL,
    categoryId BIGINT DEFAULT NULL,
    syncTagsToCategory TINYINT DEFAULT 1,
    dryRun TINYINT DEFAULT 0,
    status VARCHAR(32) DEFAULT 'running',
    totalCount INT DEFAULT 0,
    insertCount INT DEFAULT 0,
    updateCount INT DEFAULT 0,
    skipCount INT DEFAULT 0,
    errorCount INT DEFAULT 0,
    startedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    finishedAt DATETIME DEFAULT NULL,
    summary VARCHAR(1024) DEFAULT NULL,
    errorMessage TEXT DEFAULT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT DEFAULT 0,
    KEY idx_prompt_asset_import_batch_status (status),
    KEY idx_prompt_asset_import_batch_started (startedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prompt_asset_import_item (
    id BIGINT NOT NULL PRIMARY KEY,
    batchId BIGINT NOT NULL,
    sourcePairId BIGINT DEFAULT NULL,
    syncKey VARCHAR(128) DEFAULT NULL,
    targetAssetId BIGINT DEFAULT NULL,
    action VARCHAR(32) DEFAULT NULL COMMENT 'insert / update / skip / error',
    status VARCHAR(32) DEFAULT NULL,
    message VARCHAR(1024) DEFAULT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_prompt_asset_import_item_batch_id (batchId),
    KEY idx_prompt_asset_import_item_sync_key (syncKey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
