-- One-time schema and initial snapshot for the public traffic-tag page.
-- This is intentionally not a crawler or scheduled synchronization job.
-- Later changes are maintained through the OwnAI admin console or a key-authorized Agent.
CREATE TABLE IF NOT EXISTS traffic_tag (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    seedKey VARCHAR(120) NULL,
    title VARCHAR(120) NOT NULL,
    platform VARCHAR(30) NOT NULL,
    category VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    dateLabel VARCHAR(80) NOT NULL DEFAULT '',
    heat INT NOT NULL DEFAULT 0,
    tagsJson TEXT NOT NULL,
    requirementsJson TEXT NOT NULL,
    description TEXT NOT NULL,
    sourceUrl VARCHAR(1000) NOT NULL DEFAULT '',
    sortOrder INT NOT NULL DEFAULT 0,
    enabled TINYINT NOT NULL DEFAULT 1,
    sourceUpdatedTime DATETIME NOT NULL,
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_traffic_tag_seed (seedKey),
    INDEX idx_traffic_tag_public (enabled, platform, status, sortOrder),
    INDEX idx_traffic_tag_category (category),
    INDEX idx_traffic_tag_updated (sourceUpdatedTime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELETE FROM traffic_tag
WHERE seedKey IN ('betteropc-doubao-wechat', 'betteropc-doubao-jike');

INSERT IGNORE INTO traffic_tag
    (seedKey, title, platform, category, status, dateLabel, heat, tagsJson,
     requirementsJson, description, sourceUrl, sortOrder, enabled, sourceUpdatedTime)
VALUES
('betteropc-xhs-ai-common', '小红书 AI 常用流量标签', 'xiaohongshu', 'AI 工具', 'long_term', '长期有效', 999,
 '["#AI新手村","#howto系列","#AI进化生活howto","#howto入门codex","#howto入门vibecoding","#国风vibecoding","#小红书vibecoding大赛","#IP副本计划"]',
 '[]', '常用流量标签合集，适合 AI 相关内容发布时搭配使用。', '', 180, 1, '2026-09-27 03:14:00'),
('betteropc-douyin-ai-common', '抖音常用 AI 流量标签', 'douyin', 'AI 工具', 'long_term', '长期有效', 967,
 '["#我在抖音聊科技","#vibecoding大赏","#ai新星计划","#我在抖音学ai","#普通人的ai发布会"]',
 '[]', '抖音 AI 内容常用流量标签合集。', '', 170, 1, '2026-09-27 03:20:00'),
('betteropc-xhs-vibe-coding', '小红书 Vibe Coding 分类标签', 'xiaohongshu', '编程开发', 'long_term', '长期有效', 731,
 '["#vibetool｜实用工具","#vibegame｜互动游戏","#vibeart｜数字艺术","#vibeknow｜人文知识"]',
 '[]', 'Vibe Coding 内容的官方分类标签，按分类投稿可获得对应赛道流量。', '', 160, 1, '2026-09-26 04:00:00'),
('betteropc-douyin-ai-learning-support', '抖音 AI 学习类扶持', 'douyin', 'AI 教程', 'long_term', '长期有效', 674,
 '["#ai小白成长记","#我在抖音学ai","#ai实战经验"]',
 '["必须使用抖音 App 发布","完成作品回填"]',
 '符合活动范式、内容真实有参考价值，有机会获得 1500 播放量激励。抖音官方社群存在普通群→优质创作者群→特邀群分层扶持，持续稳定产出可获得更高等级扶持。',
 'https://bytedance.larkoffice.com/wiki/BONYw67H9iWPpMkY3oYcV6mTniI?sheet=Ajzc29', 150, 1, '2026-09-27 00:51:00'),
('betteropc-douyin-learn-ai-official', '我在抖音学ai｜官方话题', 'douyin', 'AI 教程', 'active', '8/7–10/30', 695,
 '["#我在抖音学ai"]', '["内容可为经验分享或求助讨论"]',
 '活动页内容方向：分享AI教程、工具玩法、提示词、工作流或学习心得，呈现所学内容、实操过程和成果，帮助新手入门。',
 'https://api.amemv.com/magic/eco/runtime/release/6a5f4064c5744d3ca3e03765?should_full_screen=1&hide_nav_bar=1&appType=douyin&activity=6a5f4064c5744d3ca3e03765', 140, 1, '2026-09-26 20:12:00'),
('betteropc-douyin-mid-autumn-national-day', '中秋国庆专项激励', 'douyin', 'AI 教程', 'active', '9/20–10/11', 53,
 '["#我的长长长假","#我在抖音学ai"]',
 '["搭配当日热点标签","内容具备互动价值或有用信息","每人每天限1篇作品享受激励"]',
 '运营公告重点投稿窗口为9月20日至10月11日。发布后2日内播放量达到1000，可获得约1000播放量激励；符合范式要求，可额外获得约2000播放量激励。每天关注群内更新的有效热点话题。',
 '', 130, 1, '2026-09-26 07:31:00'),
('betteropc-douyin-hotspot-0927', '9月27日热点', 'douyin', '数码科技', 'active', '9/27–9/27', 1,
 '["#假期我将宅家vibecoding","#宅家做个AI小游戏","#假期po图skill我已偷学","#把风景做成纪念品skill","#让AI做一个专属于我的情绪铁盒"]',
 '["仅限9月27日当天发布生效（切勿提前投稿）","必带长线话题＋当日子话题","长线话题：#我的长长长假 #我在抖音学ai"]',
 '来源：中秋国庆专项激励 AI 科技热点话题日历提前预告。话题激励仅限9月27日当天发布的作品生效，未开始前发布无法激活激励，请务必在话题日当天投稿。投稿时需搭配必带长线话题（#我的长长长假、#我在抖音学ai）+ 当日子话题。',
 '', 120, 1, '2026-09-27 02:55:00'),
('betteropc-doubao-xhs', '豆包工作｜内容创作激励计划', 'xiaohongshu', 'AI 工具', 'expired', '已失效', 582,
 '["#豆包工作"]', '[]', '豆包工作官方内容创作激励计划，当前保留小红书、抖音两个平台的数据。',
 'https://bytedance.larkoffice.com/docx/Hx9kdXuSZodrQQxB1ZycbYvmnsb', 100, 1, '2026-09-24 13:26:00'),
('betteropc-doubao-douyin', '豆包工作｜内容创作激励计划', 'douyin', 'AI 工具', 'expired', '已失效', 548,
 '["#豆包工作"]', '[]', '豆包工作官方内容创作激励计划，当前保留小红书、抖音两个平台的数据。',
 'https://bytedance.larkoffice.com/docx/Hx9kdXuSZodrQQxB1ZycbYvmnsb', 90, 1, '2026-09-26 17:24:00'),
('betteropc-douyin-hotspot-0924', '9月24日热点', 'douyin', '数码科技', 'expired', '已失效', 27,
 '["#中秋有ai也有爱","#人在家中用ai全球巡游"]', '["仅限话题日当天发布的作品"]',
 '来源：运营群提前预告。仅在对应话题日当天投稿才可生效，请勿提前投稿。', '', 70, 1, '2026-09-26 06:01:00'),
('betteropc-douyin-0920-template', '9月20日中秋与旅行范式', 'douyin', 'AI 教程', 'expired', '已失效', 19,
 '["#我的长长长假","#我在抖音学ai"]',
 '["搭配9月20日当日热点话题及本条两项长线标签","内容符合当日范式，真实且有参考价值","必须通过移动端抖音App发布","完成9月范式激励登记表的作品回填"]',
 '9月20日当日公告：用AI创作中秋作品、表达团圆心意，或制作足不出户玩转全球的旅行成片。符合当日范式要求，且内容真实、有参考价值，每人有机会获得3000播放量激励。群内另有长期不活跃移出群聊的管理要求。',
 'https://bytedance.larkoffice.com/wiki/BONYw67H9iWPpMkY3oYcV6mTniI?sheet=PBEOvT', 60, 1, '2026-09-25 22:12:00'),
('betteropc-douyin-national-day-moments', '国庆旅行朋友圈', 'douyin', '设计创意', 'expired', '已失效', 18,
 '["#国庆出去玩就这样发朋友圈"]', '["内容可为经验分享或求助讨论"]',
 '活动页内容方向：分享用AI修图、调色或生成旅行大片的方法，可展示照片前后对比。',
 'https://api.amemv.com/magic/eco/runtime/release/6a5f4064c5744d3ca3e03765?should_full_screen=1&hide_nav_bar=1&appType=douyin&activity=6a5f4064c5744d3ca3e03765', 50, 1, '2026-09-27 02:11:00'),
('betteropc-douyin-leave-genius', '本人是拼假天才', 'douyin', '效率提升', 'expired', '已失效', 11,
 '["#本人是拼假天才"]', '["内容可为经验分享或求助讨论"]',
 '活动页职场方向：分享中秋、国庆之间的拼假攻略、行程安排、机酒省钱方法或真实拼假经历。',
 'https://api.amemv.com/magic/eco/runtime/release/6a5f4064c5744d3ca3e03765?should_full_screen=1&hide_nav_bar=1&appType=douyin&activity=6a5f4064c5744d3ca3e03765', 40, 1, '2026-09-24 09:38:00'),
('betteropc-douyin-hotspot-0923', '9月23日热点', 'douyin', '数码科技', 'expired', '已失效', 11,
 '["#人在家中用ai全球巡游","#中秋有AI也有爱"]', '["仅限话题日当天发布的作品"]',
 '来源：运营群提前预告。仅在对应话题日当天投稿才可生效，请勿提前投稿。', '', 30, 1, '2026-09-24 01:28:00'),
('betteropc-douyin-ai-holiday-plan', 'AI安排国庆假期', 'douyin', 'AI 教程', 'expired', '已失效', 10,
 '["#ai把我的国庆假期安排好了"]', '["内容可为经验分享或求助讨论"]',
 '活动页内容方向：展示用AI规划国庆假期的过程，可涉及行程路线、美食、拍照安排或预算。',
 'https://api.amemv.com/magic/eco/runtime/release/6a5f4064c5744d3ca3e03765?should_full_screen=1&hide_nav_bar=1&appType=douyin&activity=6a5f4064c5744d3ca3e03765', 20, 1, '2026-09-24 06:03:00'),
('betteropc-douyin-ai-travel-transition', 'AI旅行转场', 'douyin', '设计创意', 'expired', '已失效', 9,
 '["#在学一种新的ai旅行转场"]', '["内容可为经验分享或求助讨论"]',
 '活动页内容方向：用旅行照片、城市片段或vlog制作AI转场视频，可分享制作思路、提示词或前后效果。',
 'https://api.amemv.com/magic/eco/runtime/release/6a5f4064c5744d3ca3e03765?should_full_screen=1&hide_nav_bar=1&appType=douyin&activity=6a5f4064c5744d3ca3e03765', 10, 1, '2026-09-24 06:19:00');
